$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  resources:
    type: string
    description: Path to resources.yaml file
  samples:
    type: string
    description: Path to samples.tsv file
  units:
    type: string
    description: Path to units.tsv file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  reference:
    type: object
    properties:
      fasta:
        type: string
        description: path to reference fasta file
    required:
      - fasta
  required:
    - samples
    - units
    - resources
    - default_container
    - reference
