resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

modules:
  parabricks: "develop"
  prealignment: "develop"

default_container: "docker://hydragenetics/common:0.0.1"

reference:
  fasta: "reference/reference.fasta"
  sites: "reference/reference.fasta"

cnvkit_access:
  container: "docker://marrip/cnvkit:0.9.9"
  min_gap_size: 10000

cnvkit_batch_pon:
  container: "docker://marrip/cnvkit:0.9.9"
